### ISSUE TITLE
Custom Location of Jupyter

### ISSUE THREAD

**Issue by ghost** [lorenzo2897/vscode-ipe#164]
Thanks a lot for your work on neuron, hope it will keep on expanding and improving.

Would it be possible to add an option to specify the location for Jupyter? I am using Python extension with a custom conda environment saved in the settings ("python.pythonPath") - neuron is not picking up on this, and there is no way that I can see to set it up.

**Comment by LukeyQ1** [comment]
This is a similar issue to issue #162 so I’ll close this one and bundle it with that.

**Comment by ghost** [comment]
Ah sorry, completely missed it!
