### ISSUE TITLE
IPE: Open Output Pane -> "The IPE extension requires Jupyter to be installed"

### ISSUE THREAD

**Issue by mr-ubik** [lorenzo2897/vscode-ipe#166]
I have installed `neuron` from the Marketplace, however when I try to `IPE: Open Output Pane` it always triggers the message `The IPE extension requires Jupyter to be installed` even if I do have Jupyter installed.

**Comment by sainathadapa** [comment]
I face the same issue as well. Did anyone figure out a solution yet?

**Comment by LukeyQ1** [comment]
I believe this maybe a similar issue to issue #162 where its using the wrong path for Juypter so I’ll close this one and bundle it with that.
