### ISSUE TITLE
Integration with pipenv

### ISSUE THREAD

**Issue by zhenyakovalyov** [lorenzo2897/vscode-ipe#171]
I use pipenv to manage project dependencies. It looks like neuron uses the default python environment:

<img width="677" alt="screenshot 2018-10-24 at 16 32 00" src="https://user-images.githubusercontent.com/10375041/47442545-6abd4080-d7aa-11e8-95d6-5b2b406c2c6f.png">

Is there any way I can trigger the environment change for neuron?

**Comment by LukeyQ1** [comment]
This is a similar issue to #161 and #162 so I'm going to close this one. This is the most requested feature and we would like to work on this soon.

**Comment by pavanagrawal123** [comment]
@zhenyakovalyov fixed it here: https://github.com/pavanagrawal123/VSNotebooks/pull/10

try it out and let me know if it works!
