### ISSUE TITLE
Recognize current path automatically

### ISSUE THREAD

**Issue by virtualdvid** [lorenzo2897/vscode-ipe#177]
I'm running a code and neuron is not recognizing the current path, so I have to add an extra line with it `os.chdir('C:\\Users\\user\\github\\gapml\\CV\\gapcv')`. How can I avoid this? and how can I restart the kernel?

**Comment by pavanagrawal123** [comment]
Check my fork! https://github.com/pavanagrawal123/VSNotebooks, it's fixed there :) All changes *can* be upstreamed as soon as this repo is active again :)

**Comment by LukeyQ1** [comment]
There is a command in the Colman’s palette to restart to the kernel (https://github.com/lorenzo2897/vscode-ipe/wiki/Design-Specification)

I’m afraid current path is a know issue #167 and so atm you need to add that extra line. :(
I’m going to close this issue and bundle it with the previous
